# -*- coding: utf-8 -*-
import jinja2
import os
import pymongo
import boto
from email.mime.application import MIMEApplication
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from datetime import datetime, date, timedelta
from boto.ses import connection
from email.utils import parseaddr

env = jinja2.Environment(
    loader=jinja2.FileSystemLoader(os.path.dirname(__file__)),
    extensions=['jinja2.ext.autoescape'],
    autoescape=True
)

client = pymongo.MongoClient()
db = client.epihack
projection = {"email": 1, "platform": 1}
# query = {
#     "email":{"$nin": ["juliocsmelo@gmail.com",
#     "onicio@gmail.com", "mariana.nacarato@gmail.com",
#     "douglasq16@gmail.com", "sfilhu@gmail.com", "mrblondepitrack@gmail.com"]}
# }
query = {
    '$and': [
        {'country': {'$exists': true}},
        {'country': 'Brazil'},
        {'email':
            {
                '$nin': ["chmirandagomes@gmail.com",
                "anareginaenf@gmail.com",
                "morais.costa3@hotmail.com",
                "belmaciel@gmail.com",
                "dedecfc2014@gmail.com",
                "patipat@opendream.co.th",
                "fernandafnascimento@gmail.com",
                "juliadealbuquerque@gmail.com",
                "mariana+gds@epitrack.com.br",
                "cristina_nacarato@hotmail.com",
                "mariananacarato@gmail.com",
                "valeriasg2003@yahoo.com.br",
                "graziellacmendonca@gmail.com",
                "jessicacerilo@gmail.com",
                "reichert.br@gmail.com",
                "moniquefelixx@gmail.com",
                "luan_cuiabano@hotmail.com",
                "tuliateste@teste.com",
                "franzteste@teste.com",
                "ecavalcanti@gmail.com",
                "martaps19@yahoo.com.br",
                "douglas5@epitrack.com",
                "lemosandrecosta@gmail.com",
                "thaissoliver@hotmail.com",
                "moreira.alana@gmail.com",
                "danicerqueirabatista@gmail.com",
                "tainsuppi@gmail.com",
                "cirodemolay@gmail.com",
                "croteste@teste.com",
                "nathy.goncalvesl@outlook.com",
                "lhbandeira@hotmail.com",
                "gabriel.ferreira63@gmail.com",
                "orzeu.guido@hotmail.com",
                "tinateste@teste.com",
                "krauso.dsm@hotmail.com",
                "veralice@terra.com.br",
                "martaorofino@gmail.com",
                "silviaspiel@gmail.com",
                "nielza.silva.123@gmail.com",
                "onyde@hotmail.com",
                "gleide@saude.gov.br",
                "cleuburtet@hotmail.com",
                "fernandom@saude.gov.br",
                "wafalmeida@gmail.com",
                "skboiteux@gmail.com",
                "niagara.r.braga@gmail.com",
                "talitaferrazlyra@hotmail.com",
                "pauloabilio@gmail.com",
                "xbarcellos@gmail.com",
                "anybene@hotmail.com",
                "angel.barreto@hotmail.com",
                "carlabasso91@hotmail.com",
                "jozelia.pimentel@hotmail.com",
                "beltraoh@gmail.com",
                "jvcabral2009@hotmail.com",
                "dbardui@gmail.com",
                "valeskacostaa25@gmail.com",
                "thulioph@gmail.com",
                "miqueias.lopes@gmail.com",
                "raexclama@gmail.com",
                "squaq@epitrack.com",
                "meninaepitrack@epitrack.com",
                "anclar.patric@hotmail.com",
                "isabela.isis.alves@gmail.com",
                "nata-santana@hotmail.com",
                "silvana.bocanegra@gmail.com",
                "bocanegra.willian@gmail.com",
                "aos@cin.ufpe.br",
                "edvan_xp@hotmail.com",
                "capramc@gmail.com",
                "dudamaillari@gmail.com",
                "amandinhasc@gmail.com",
                "marturcato@gmail.com",
                "gabihage@hotmail.com",
                "marcia.pragana@gmail.com",
                "hugo.victor@outlook.com",
                "nataliarobertasg@gmail.com",
                "eddwan@gmail.com",
                "mateusleiteodonto@outlook.com",
                "ellen.biogoncalves@hotmail.com",
                "jujubms@hotmail.com",
                "cyprianogarcia@gmail.com",
                "coloraroteste@teste.com",
                "sabrina-vizeu@saude.rs.gov.br",
                "epitracktesterpm@gmail.com",
                "joelmlima.rr@gmail.com",
                "mongoteste@teste.com",
                "mongateste@teste.com",
                "thiagoolsilva@gmail.com",
                "natan.monsores@gmail.com",
                "danirodrigues.to@gmail.com",
                "nata.vet64@gmail.com",
                "lfwaib@gmail.com",
                "igorepitrack@gmail.com",
                "damaris.guerravs@gmail.com",
                "fabianamalaspina@gmail.com",
                "carolgontijo81@gmail.com",
                "rubenitafofa@gmail.com",
                "kfersan@yahoo.com.br",
                "ifornivieira@gmail.com",
                "liliapiresdossantos@gmail.com",
                "mpzaitune@gmail.com",
                "s.faire@hotmail.com",
                "evertonsquaq@gmail.com",
                "silvaivan744@gmail.com",
                "nielsonnas@gmail.com",
                "mariameliaborba@gmail.com",
                "douglas2@epitrack.com.br",
                "vicente.paixao@autostar.com.br",
                "barros.gerald@gmail.com",
                "zetaec27@gmail.com",
                "calvesbahia@gmail.com",
                "lgrivero@gmail.com",
                "alexsandromenezes32@bol.com.br",
                "tamiresalbuquerqueacre@gmail.com",
                "adeli.medeiros@hotmail.com",
                "miqsoftware1@hotmail.com",
                "thiagorafaelps@gmail.com",
                "alexsandromenezes32@bom.com.br",
                "emaildorenatostrauss@gmail.com",
                "joseteste@teste.com",
                "johnilsonbatista@gmail.com",
                "raphael.reis.coelho@hotmail.com",
                "brunorezegue@gmail.com",
                "deborarochabsb@gmail.com",
                "arnaldovono@gmail.com",
                "gds1+jgabriel.ufpa@gmail.com",
                "j.gilberto_direito@hotmail.com",
                "douglas4@epitrack.com",
                "mpoltosi@gmail.com",
                "fernandodeisis@gmail.com",
                "costajr815@gmail.com",
                "lagomedeiros@oi.com.br",
                "daniela.buosi@gmail.com",
                "magdazinhalove@gmail.com",
                "valmachado7@gmail.com",
                "gabryellareginaa@gmail.com",
                "aelsonfigueiredo3@gmail.com.br",
                "nandalougomes@gmail.com",
                "testador@teste.com",
                "zefinhateste@teste.com",
                "danivaz26@gmail.com",
                "zecateste@teste.com",
                "gds@gds.com",
                "darcybuss@gmail.com",
                "rdamiski@yahoo.com.br",
                "gustavommaia@hotmail.com",
                "angrawb@gmail.com",
                "rivosan@gmail.com",
                "aderval82@gmail.com",
                "rafaelwesley2015@hotmail.com",
                "codgomes@gmail.com",
                "isabellepolli@hotmail.com",
                "fenyx2410@hotmail.com",
                "toninhomm1@gmail.com",
                "rodrigo.wander@hotmail.com",
                "freitas.lucia@gmail.com",
                "adelanio.moura@gmail.com",
                "hungriayasmin@hotmail.com",
                "louis.anderson33@gmail.com",
                "flaschbizzybone@gmail.com",
                "richardbb@ymail.com",
                "lucileidebps@gmail.com",
                "gonanalista2012@gmail.com",
                "daniloqueiroz.ti@gmail.com",
                "pedromfer@outlook.com",
                "alinemgurgel@hotmail.com",
                "fames78@hotmail.com",
                "sanjoaldo@hotmail.com",
                "reginaldo-augustodasilva@hotmail.com",
                "prof.jstos@gmail.com",
                "luiz@zerograu.ind.br",
                "barreiros.consultoria@creci.org.br",
                "manoel.amador13@yahoo.com.br",
                "luizantonio995@gmail.com",
                "thaismachado90@gmail.com",
                "silvapedrapreta@gmail.com",
                "cristianoom89@gmail.com",
                "robertoantero123@gmail.com",
                "evangelistasousa@gmail.com",
                "luizricardo61@hotmail.com",
                "danielacavalini@yahoo.com.br",
                "priscilaegs@gmail.com",
                "jobsouza42@gmail.com",
                "valdenilson.neves38@gmail.com",
                "mcrisleao7@gmail.com",
                "henrick1208@gmail.com",
                "fabiola.barros@yahoo.com.br",
                "azimiani@bol.com.br",
                "betosouzanobre@hotmail.com",
                "vila2104@gmail.com",
                "vivisorrisos@gmail.com",
                "meguido17@yahoo.com",
                "jotaferreirasouza@hotmail.com",
                "guilhermekroger@gmail.com",
                "chelecirino@gmail.com",
                "rebeccameriguete95@gmail.com",
                "li_diane_b@ibest.com.br",
                "joaopaulollima04@gmail.com",
                "valdo1021@gmail.com",
                "cirene27lins@hotmail.com",
                "eldascr@hotmail.com",
                "calbert-o@hotmail.com",
                "judyferreiraalves@gmail.com",
                "normaguicosta@gmail.com",
                "silasgomes326@yahoo.com.br",
                "androsuios@gmail.com",
                "ontiveros.torres@hotmail.com",
                "iara10mary@gmail.com",
                "vera_xandy@hotmail.com",
                "gustavobednarski@hotmail.com",
                "ricardoeliasthome@yahoo.com.br",
                "adinalvoaquinoj@gmail.com",
                "arturoluis@cossiozazueta.com",
                "taurus58@gmail.com",
                "braz.bene@gmail.com",
                "jucilenejsantos@gmail.com",
                "jbftec@gmail.com",
                "brunomauricio05@hotmail.com",
                "medeirosjosevicentemedeiros@gmail.com",
                "gmiglio@gmail.com",
                "ffgoncalves1981@gmail.com",
                "enfermeiroedilon@gmail.com",
                "jose11.jc36@gmail.com",
                "eletronicanunes@gmail.com",
                "contato_inteligent@hotmail.com",
                "wmanjos@gmail.com",
                "ivna.pires@gmail.com",
                "enoirjosevaz18@gmail.com",
                "antoniocafaria@hotmail.com",
                "joker@epitrack.com",
                "vanessa.santos.barbosa.vs@gmail.com",
                "monalisa-paiva@hotmail.com",
                "kaaah.godoi@hotmail.com",
                "adelyany@hotmail.com",
                "rcia@hotmail.com",
                "ducileidesantos@hotmail.com",
                "ritadeluzia13@hotmail.com",
                "valderina_star@hotmail.com.br",
                "helena.flor@hotmail.com",
                "isabelaesm@gmail.com",
                "luanaracarvalho@hotmail.com",
                "heloisa.constantino@gmail.com",
                "frsouza.psi@gmail.com",
                "camila.keyla@gmail.com",
                "zelandiasilveira@gmail.com",
                "emiliagr@gmail.com",
                "mizabel0903.ig@gmail.com",
                "natanaelnestrach@gmail.com",
                "rafaelapereira86@hotmail.com",
                "viviluarosa@gmail.com",
                "tilaramaravilha8@gmail.com",
                "bih.ibm@gmail.com",
                "sacfotonantes@gmail.com",
                "pliniopalacio95@gmail.com",
                "mikael.araujo22@live.com",
                "aline.senhorine@hotmail.com",
                "fran_trombelli@hotmail.com",
                "marjmarjany@hotmail.com",
                "ja.isi@hotmail.com",
                "andreiadantas.barros@gmail.com",
                "aline.abento.ab@gmail.com",
                "danypst@hotmail.com",
                "sandrojoserisso@gmail.com",
                "paulianacoelhogarcia@outlook.com",
                "alexandrebelchor@hotmail.com",
                "wallita09@hotmail.com",
                "moisespirozzi@live.com",
                "romulorbeirigo@hotmail.com",
                "stellalemke@gmail.com",
                "gatasky@hotmail.com",
                "ricardo.rocha@apoio.com.vc",
                "eugeniapaiva88@hotmail.com",
                "torresalmeidamonique@gmail.com",
                "morety_nf@hotmail.com",
                "rosan_andrade@hotmail.com",
                "machinerfernanda@gmail.com",
                "ivinagrangeiro@gmail.com",
                "niedmagrangeiro@gmail.com",
                "t.penelope@hotmail.com",
                "taise.leal@yahoo.com.br",
                "alebueno2@yahoo.com.br",
                "kk@kk.com",
                "gonzagarf2015@gmail.com",
                "jack_trajano@hotmail.com",
                "claudisj_lon@hotmail.com",
                "amnda.siqueiranas@gmail.com",
                "roberto.bauer@saude.gov.br",
                "jfreitashbl@gmail.com",
                "mikael_cpc@hotmail.com",
                "sebastiaopaularodrigues@gmail.com",
                "ac.salatini@gmail.com",
                "marifilonutri@hotmail.com",
                "ygasperoni@bol.com.br",
                "hericacorrea18@gmail.com",
                "deboradc@gmail.com",
                "jupira.pedroso@hotmail.com",
                "joaobatista.psico@hotmail.com",
                "joseliomarinho@gmail.com",
                "neusarios@hotmail.com",
                "ericahjrenf@gmail.com",
                "victorboff@hotmail.com",
                "janileidealbuquerque@gmail.com",
                "carolineassantos@gmail.com",
                "yulienbrasil@gmail.com",
                "keila_viana@hotmail.com",
                "marcelofaria-_-1@hotmail.com",
                "paulomenezes@outlook.com",
                "evaldo.leite@saude.gov.br",
                "edeziaguirra@hotmail.com",
                "monica1971costa@gmail.com",
                "shirleide_santos@yahoo.com.br",
                "milca-farma@hotmail.com",
                "luiz-gc@hotmail.com",
                "vivianef474@gmail.com",
                "tinasborges@yahoo.com.br",
                "evertonsousa113@gmail.com",
                "fisiologia.samuel@gmail.com",
                "juniorego0506@hitmail.com",
                "hhhuiara@gmail.com",
                "alinerepolez@gmail.com",
                "msbj_enf@yahoo.com.br",
                "lbranquinhon@gmail.com",
                "danivieira1@hotmail.com",
                "viniciusmarim@yahoo.com.br",
                "gisnick@hotmail.com",
                "eloisabs@yahoo.com.br",
                "carol._.cavalcantr@hotmail.com",
                "marciarezende75@gmail.com",
                "moacir.deves@gmail.com",
                "moni_kashion@yahoo.com.br",
                "polinegabriela@bol.com.br",
                "tinraphael@gmail.com",
                "fernandinho.up@terra.com.br",
                "hirancintra@outlook.com.br",
                "dannydog78@hotmail.com",
                "arianatyskanunes@hotmail.com",
                "eduardo.rybeiro@hotmail.com",
                "kellynhaluizasales@gmail.com",
                "taina_santos12@hotmail.com",
                "mudacruzeiro@yahoo.com.br",
                "edsonladainhamg@gmail.com",
                "willmalog2014@gmail.com",
                "anekellb@gmail.com",
                "thatamiranda@hotmail.com",
                "grazi_psy@hotmail.com",
                "leticiarodriguesalvarenga@gmail.com",
                "cosmelaurindo@msn.com",
                "ketelenpsico@yahoo.com.br",
                "alinenilags@gmail.com",
                "deoliveirafreitascelia@gmail.com",
                "marcia.ianelli@uol.com.br",
                "carolineschirmer@yahoo.com.br",
                "cidmilleo@hotmail.com",
                "luanery@live.com",
                "luanemoura@hotmail.com",
                "ivie.ananda@gmail.com",
                "ma.bassuncao@gmail.com",
                "mila_pedreira@hotmail.com",
                "fd.reis@yahoo.com.br",
                "kpskarina@gmail.com",
                "paulohdom@gmail.com",
                "diana.gs@icloud.com",
                "leandroclaudio@gmail.com",
                "marcelo.lima@saude.gov.br",
                "lucasvieirad2@gmail.com",
                "reluphilo@hotmail.com",
                "joao.alves@saude.gov.br",
                "soniammo@uol.com.br",
                "rodlemos100@gmail.com",
                "ludovico.13i@hotmail.com",
                "clautchica10@hotmail.com",
                "pedro.milhome@hotmail.com",
                "fabiocardosoreis@yahoo.com.br",
                "andrea.araujo4@gmail.com",
                "eliana.moutinho@ymail.com",
                "enfmillabezeera@hotmail.com",
                "tonabisbrasil@hotmail.com",
                "andre.mesquita@b2t.com.br",
                "pcoury@gmail.com",
                "jmarcos357@gmail.com",
                "mmfgbalieiro@uol.br",
                "rsaorim@gmail.com",
                "lucasw.junges@hotmail.com",
                "fabiifontes@msn.com",
                "luscleide@gmail.com",
                "olgaloreena.lisboa@gmail.com",
                "kecasbampato@hotmail.com",
                "mandelli03@gmail.com",
                "sibeleindreli@hotmail.com",
                "eulina12@hotmail.com",
                "natalyrcqueiroz@yahoo.com.br",
                "pittydasilva@hotmail.com",
                "renato.wanderley@hotmail.com",
                "pamela_liarena@hotmail.com",
                "rosinele0602@hotmail.com",
                "eliane.assis@saude.gov.br",
                "patrickalmeida1@hotmail.com",
                "paullallino@hotamail.com",
                "dilvadaniely@hotmail.com",
                "leo.madruga@gmail.com",
                "farmagislenenardi@gmail.com",
                "martins_oliveira63@hotmail.com",
                "verissimoigor17@gmail.com",
                "helianesuely@hotmail.com",
                "rmr.silva1@gmail.com",
                "heraldo.simoes@uece.br",
                "jeanmaxado@yahoo.com.br",
                "erikamaximo19@gmail.com",
                "eugeniaaragao@icloud.com",
                "darinholisboa.dl@gmail.com",
                "jeh.srodrigues@gmail.com",
                "maxprinz@gmail.com",
                "aias.alves@hotmail.com",
                "vivis_ss@uberabadigital.com.br",
                "janyjussara@yahoo.com.br",
                "junilsif@hotmail.com",
                "adailtonmorais10@gmail.com",
                "nyyamamoto@hotmail.com",
                "robertapspina@gmail.com",
                "veragrillo@fiocruz.br",
                "emilymaviana@gmail.com",
                "antonio.sousa@saude.gov.br",
                "luizmendes06@yahoo.com.br",
                "andrealangevin@gmail.com",
                "fabygomesrj@gmail.com",
                "leticiaramos53@gmail.com",
                "maralgravinatti@gmail.com",
                "karlacfslourenco@gmail.com",
                "nandinha_sousa17@hotmail.com",
                "arthur_viz@hotmail.com",
                "eduardomotacartier@gmail.com",
                "jarlanecaldas@outlook.com",
                "crisana80@hotmail.com",
                "thaisvbrandao@hotmail.com",
                "alisonfabricio.vilelinha@hotmail.com",
                "victoriarujo@yahoo.com.br",
                "denise-zuque@hotmail.com",
                "angela.velho@terra.com.br",
                "marinasmelo@yahoo.com.br",
                "gedean.dias@gmail.com",
                "regacp@hotmail.com",
                "camilaalvesccaa@gmail.com",
                "megvcruz@hotmail.com",
                "limaneto5@gmail.com",
                "myllenem@outlook.com",
                "fulanoteste@teste.com",
                "georgeteste@teste.com",
                "lenonteste@teste.com",
                "marco.costa63@gmail.com",
                "elisabel_salim@hotmail.com",
                "jeyzaanyele@gmail.com",
                "felipetduailibe@hotmail.com",
                "voador@teste.com",
                "karanalpe@gmail.com",
                "josecamposifmt@gmail.com",
                "priscilafbeck@gmail.com",
                "slpimentel@hotmail.com",
                "tuliocampos@gmail.com",
                "julio.cesargnv@hotmail.com",
                "anacarolina35@live.com",
                "mbvm1965@hotmail.com",
                "robzerra.silva@gmail.com",
                "jbcnegocioos@gmail.com",
                "josefernandob@gmail.com",
                "valeriakaren01@gmail.com",
                "levigato2014@hotmail.com",
                "igor.morais@gmail.com",
                "eu@hotmail.com",
                "alane.steixeira@gmail.com",
                "cleber.wew@gemeil.com",
                "jeancarloslivre@gmail.com",
                "anselmo.antunes@gmail.com",
                "jorgeramalho2009@gmail.com",
                "paloma.mmpe@gmail.com",
                "p.polez@outlook.com",
                "felipetduailibe@yahoo.com.br",
                "rebecabb@saude.gov.br",
                "alex_spc@hotmail.com",
                "rebecabbonfim@gmail.com",
                "emerson.araujo@saude.gov.br",
                "jaqueliners1@hotmail.com",
                "leandroluiz8@hotmail.com",
                "nuplace.consultoria@gmail.com",
                "rafaelahpinto@gmail.com",
                "vchiozi@bol.com.br",
                "febenicio@hotmail.com",
                "cleo.auditoria@hotmail.com",
                "saletecalaca@gmail.com",
                "luizhenrique.diasdemello1@gmail.com",
                "deborafory@me.com",
                "edufer52@hotmail.com",
                "silvasaqua@hotmail.com",
                "Wallet@uol.com.br",
                "thiago-lima155@hotmail.com",
                "mcdowell@uol.com.br",
                "jose-augusto-22@hotmail.com",
                "tatianec279@gmail.com",
                "markitoceno@gmail.com",
                "ceciliaramosnutri@gmail.com",
                "dicosantos@gmail.com",
                "sonia_terezeredo@hotmail.com",
                "soniaorquiza@gmail.com",
                "elzinhalia1982@hotmail.com",
                "oclamordasaguas@censanet.com.br",
                "ceroki04@yahoo.com.br",
                "leticiapoletti@gmail.com",
                "v.deana@hotmail.com",
                "rossavivian@gmail.com",
                "manunasser@yahoo.com.br",
                "53pinkroses@gmx.com",]
            }
        }
    ]
}
users_cursor = db.user.find(query, projection)

def send_ses(fromaddr,
             subject,
             body,
             recipient,
             attachment=None,
             filename=''):
    """Send an email via the Amazon SES service.

    Example:
      send_ses('me@example.com, 'greetings', "Hi!", 'you@example.com)

    Return:
      If 'ErrorResponse' appears in the return message from SES,
      return the message, otherwise return an empty '' string.
    """
    msg = MIMEMultipart('alternative')
    msg['Subject'] = subject
    msg['From'] = fromaddr
    msg['To'] = recipient
    part1 = MIMEText(body, 'html')
    msg.attach(part1)
    if attachment:
        part = MIMEApplication(attachment)
        part.add_header('Content-Disposition', 'attachment', filename=filename)
        msg.attach(part)
    conn = boto.ses.connect_to_region(
        'us-east-1',
        aws_access_key_id='AKIAJQ4NOCWSRY7OXS4Q',
        aws_secret_access_key='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')
    result = conn.send_raw_email(msg.as_string())
    return result if 'ErrorResponse' in result else ''

def send_remider():
    total = 0
    for user in users_cursor:
        url = "https://guardioesdasaude.org/"
        if user['platform'] == "ios":
            url = "http://kernel.guardioesdasaude.org/mobimail"
        country = user.get('country', 'Brazil')
        template_name = 'paralimpiadas.pt.html'
        template = env.get_template(template_name)
        html_body = template.render(the_url=url)
        try:
            print('sending to: {0}'.format(user['email']))
            send_ses('contato@guardioesdasaude.org', 'As Paralimpíadas já começaram!', template.render(the_url=url).encode( "utf-8" ), user['email'])
        except:
            pass
        total +=1
    print('Total de e-mail enviados {total}'.format(total=total))


if __name__ == "__main__":
    send_remider()
